export const SEARCH_BY_ABN_REQUEST = "SEARCH_BY_ABN_REQUEST";
export const SEARCH_BY_ABN_COMPLETED = "SEARCH_BY_ABN_COMPLETED";
export const SEARCH_BY_NAME_REQUEST = "SEARCH_BY_NAME_REQUEST";
export const SEARCH_BY_NAME_COMPLETED = "SEARCH_BY_NAME_COMPLETED";
export const SEARCH_ERROR = "SEARCH_ERROR";
export const VIEW_ABN_REQUEST = "VIEW_ABN_REQUEST";
export const VIEW_ABN_COMPLETED = "VIEW_ABN_COMPLETED";
export const PROCESSING_REQUEST = "PROCESSING_REQUEST";
